### ISSUE TITLE
custom config.gateway.json for advanced USG setup

### ISSUE THREAD

**Issue by pho3nixf1re** [jacobalberty/unifi-docker#121]
What is the correct way to provide a custom `config.gateway.json` for advanced configuration of the USG? Primarily this is needed for mapping DNS addresses on my LAN. This file needs to persist so I imagine it would have to be a mounted volume. Would that work or cause unexpected issues down the line?

### Host operating system

`Linux feliciterra-server 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux`

### What tag are you using

Example: `latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```yaml
version: '3'
services:
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:latest
    restart: always
    environment:
      VIRTUAL_HOST: <redacted>
      VIRTUAL_PORT: 8443
      VIRTUAL_PROTO: https
      LETSENCRYPT_EMAIL: <redacted>
      LETSENCRYPT_HOST: <redacted>
    volumes:
      - ./data/unifi:/unifi
    ports:
      - "8080:8080/tcp"
      - "3478:3478/udp"
      - "6789:6789/tcp"
      - "10001:10001/udp"
    networks:
      - webproxy
networks:
  webproxy:
    external:
      name: webproxy
```

### What do you expect to happen?

N/A

### What actually happens?

N/A
