### ISSUE TITLE
Set other MongoDB user than 999

### ISSUE THREAD

**Issue by daniel-lerch** [jacobalberty/unifi-docker#144]
### Host operating system

Ubuntu 18.04.1 LTS

### What tag are you using

`latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```yaml
version: '2.2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - unifi
    restart: always
    volumes:
      - ./data/db:/data/db
  controller:
    image: "jacobalberty/unifi:latest"
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - ./data/data:/unifi/data
      - ./data/log:/unifi/log
      - ./data/cert:/unifi/cert
      - ./data/init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      RUNAS_UID0: "false"
      UNIFI_UID: 33
      UNIFI_GID: 33
    ports:
      - "8442:8442"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - ./data/log:/unifi/log

networks:
  unifi:
```

### What do you expect to happen?

I would expect the UniFi controller to run with user 33/www-data).

### What actually happens?

The UniFi controller itself runs with user 33/www-data. Directory permissions are correctly set at the container's first run. However the `db` directory is still owned by user 999 and `mongod` operates with user 999.

### Conclusion

I would like `mongod` either run with `UNIFI_GID` or a separate environment variable that should be documented in this project's README.

**Comment by daniel-lerch** [comment]
I have just looked into this old issue again.

MongoDB is operated by a separate container whose `uid` can be set either by `docker run --user "33:33" mongo:3.4` or in the Compose file:

```yaml
version: '2.2'
services:
  mongo:
    image: mongo:3.4
    user: "33:33"
    networks:
      - unifi
    restart: always
    volumes:
      - ./data/db:/data/db
```

Just because UniFi Docker and MongoDB are both using `999` as default `uid` does not mean that these applications live in the same container.
