### ISSUE TITLE
import_cert should support EC private keys

### ISSUE THREAD

**Issue by jpawlowski** [jacobalberty/unifi-docker#148]
### Host operating system
Ubuntu Server latest

### What tag are you using
latest

### What complete docker command or docker-compose.yml do you use to launch the container 
````
  unifi:
    image: "jacobalberty/unifi:latest"
    depends_on:
      - pki
    init: true
    networks:
      - net
    restart: always
    volumes:
      - ./unifi/data/:/unifi/data/
      - ./unifi/log/:/unifi/log/
      - ./unifi/init.d.local/:/usr/local/unifi/init.d/
      - ./pki/fifo/server/ecc/unifi/:/certs/:ro
    environment:
      RUNAS_UID0: "false"
      TZ: "Europe/Berlin"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "3478:3478/udp"
      - "6789:6789"
      - "10001:10001/udp"
`````

### What do you expect to happen?

Custom pre-init script provides pre-created certificates from local PKI:

`````
#!/bin/sh

while [ true ]; do
  if [ -s /certs/unifi.req.signed ]; then
    break
  elif [ -s /certs/unifi.req.error ]; then
    echo "CSR signing error:"
    cat /certs/unifi.req.error.txt
    exit 10
  elif [ -f /certs/unifi.req.processing ]; then
    echo "CA is processing CSR: $(cat /certs/unifi.req.processing) ..."
  elif [ -f /certs/unifi.req ]; then
    echo "Waitiung for CA to provide certificate ..."
  fi
  sleep 10
done

cd /certs
cp -f unifi.crt /unifi/cert/cert.pem
cp -f unifi.nopasswd.key /unifi/cert/privkey.pem
cp -f ca-chain.crt /unifi/cert/chain.pem
`````
The private CA uses elliptic curve based private keys and certificates as a default.
The certificate import to the Java keystore should support such type of certificates.

### What actually happens?
The `import_cert` uses static certificate type RSA ans therefore fails to successfully import EC based keys.
