### ISSUE TITLE
5.9.29 fails build

### ISSUE THREAD

**Issue by EricReiche** [jacobalberty/unifi-docker#153]
### Host operating system

 Ubuntu 17.10

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker-compose up -d --build --remove-orphans`

```
    unifi-controller:
        container_name: unifi.controller
        build:
            context: https://github.com/jacobalberty/unifi-docker.git#beta
            args:
                PKGURL: https://dl.ubnt.com/unifi/5.9.29/unifi_sysvinit_all.deb
        restart: always
        volumes:
            - '/docker/unifi/lib:/var/lib/unifi'
            - '/docker/unifi/log:/var/log/unifi'
            - '/docker/unifi/run:/var/run/unifi'
        networks:
            physical:
                ipv4_address: 192.168.xx.xxx
        environment:
            - TZ=Europe/Berlin
        labels:
            - 'unifi-controller'
```

### What do you expect to happen?
Container to be built

### What actually happens?

```
Reading package lists...
E: Sub-process Popen returned an error code (2)
E: Encountered a section with no Package: header
E: Problem with MergeList /unifi.deb
E: The package lists or status file could not be parsed or opened.
ERROR: Service 'unifi-controller' failed to build: The command '/bin/sh -c set -ex  && mkdir -p /usr/share/man/man1/  && groupadd -r unifi -g $UNIFI_GID  && useradd --no-log-init -r -u $UNIFI_UID -g $UNIFI_GID unifi  && /usr/local/bin/docker-build.sh "${PKGURL}"' returned a non-zero code: 100
```
