### ISSUE TITLE
docker-compose.yml + Traefik Reverse proxy question

### ISSUE THREAD

**Issue by sesshomaru86** [jacobalberty/unifi-docker#162]
Hello guys . i would like to implement Traefik on the unifi container but as i have installed the container though the docker-compose file i'm not quite sure if i will configure it correct. So before i break everything i'm kindly ask for your help and expertise. I know it is not exactly an issue but probably it's the best place where i can get an answer. As i have implemented traefik in other services as tautulli,transmission,etc i usually  add to the compose file 

networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=service"
      - "traefik.frontend.rule=Host:service.${DOMAINNAME}"
      - "traefik.port=443"
      - "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

In the compose file of unifi although should i replace the network unifi with "traefik_proxy" that i have created  and add in the end the labels?

version: '2.2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - traefik_proxy
    restart: always
    volumes:
      - db:/data/db
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    depends_on:
      - mongo
    init: true
    networks:
      - traefik_proxy
    restart: always
    volumes:
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*'
    restart: always
    volumes:
      - log:/unifi/log

volumes:
  db:
  data:
  log:
  cert:
  init:

networks:
  traefik_proxy:
labels:
- "traefik.enable=true"
- "traefik.backend=service"
- "traefik.frontend.rule=Host:service.${DOMAINNAME}"
- "traefik.port=443"
- "traefik.protocol=https"
- "traefik.docker.network=traefik_proxy"
- "traefik.frontend.headers.SSLRedirect=true"
- "traefik.frontend.headers.STSSeconds=315360000"
- "traefik.frontend.headers.browserXSSFilter=true"
- "traefik.frontend.headers.contentTypeNosniff=true"
- "traefik.frontend.headers.forceSTSHeader=true"
- "traefik.frontend.headers.SSLHost=example.com"
- "traefik.frontend.headers.STSIncludeSubdomains=true"
- "traefik.frontend.headers.STSPreload=true"
- "traefik.frontend.headers.frameDeny=true"

Thanx once again !

**Comment by phroggster** [comment]
The traefik configuration labels should be scoped to the controller service (as opposed to getting [silently ignored](https://docs.traefik.io/configuration/backends/docker/#using-docker-compose) at the end of the yaml), and traefik.port should likely be changed to 8443.

```yml
version: '2.2'
services:
  mongo:
    {snip}
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    depends_on:
      - mongo
    init: true
    networks:
      - traefik_proxy
    restart: always
    volumes:
      - data:/unifi/data
      - log:/unifi/log
      - cert:/unifi/cert
      - init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8443"
     {snip}
 logs:
    {snip}
volumes:
{snip}
networks:
{snip}
```

Other than those minor tweaks, that should hopefully get you up and running.
