### ISSUE TITLE
Latest Beta Error: "We do not support upgrading from 5.10.12"

### ISSUE THREAD

**Issue by toolpanda** [jacobalberty/unifi-docker#169]
### Host operating system

`Debian stretch` 

### What tag are you using

`beta`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
version: "3"

networks:
  web:
    external:
      name: web

volumes:
  unifiController:
    driver_opts:
      type: "nfs"
      o: "addr=10.10.101.15,rw,hard,nolock"
      device: ":/mnt/tank/docker/unifiController"

services:
  reverseProxy:
    image: traefik
    command: --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/a/docker/traefik/traefik.toml:/traefik.toml
      - /home/a/docker/traefik/rules.toml:/rules.toml
      - /home/a/docker/traefik/acme.json:/acme.json
    ports:
      - "80:80"
      - "443:443"
    container_name: traefik
    environment:
      - CF_API_EMAIL=omitted
      - CF_API_KEY=omitted
      - TZ=America/Vancouver
    labels:
      - traefik.port=8080
      - traefik.frontend.rule=Host:monitor.mydomain.com
      - traefik.docker.network=web
      - com.centurylinklabs.watchtower.enable=true
    deploy:
      restart_policy:
        condition: always
    networks:
      - web
  unifiManagement:
    image: jacobalberty/unifi:beta
    volumes:
      - unifiController:/unifi
    ports:
      - "3478:3478/udp"
      - "8080:8080"
      - "10001:10001/udp"
    container_name: unifi
    environment:
      - TZ=America/Vancouver
      - JVM_MAX_THREAD_STACK_SIZE=1280k
      - UNIFI_GID=972
      - UNIFI_UID=921
      - RUNAS_UID0=false
      - BIND_PRIV=false
      - PKGURL=https://dl.ubnt.com/unifi/5.10.12-20644d4901/unifi_sysvinit_all.deb
    labels:
      - traefik.protocol=https
      - traefik.port=8443
      - traefik.frontend.rule=Host:unifi.mydomain.com
      - traefik.docker.network=web
      - com.centurylinklabs.watchtower.enable=true
    deploy:
      restart_policy:
        condition: always
    networks:
      - web
    depends_on:
      - reverseProxy
  updater:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command:  --cleanup --label-enable
    environment:
      - TZ=America/Vancouver
    labels:
      - com.centurylinklabs.watchtower.enable=true
    deploy:
      restart_policy:
        condition: always
```

### What do you expect to happen?
I expect there to be PKGURL environment variable respected and beta version downloaded
### What actually happens?
Nothing in the logs shows expected things happening, it just starts pre-built version of the controller.

```
[2019-02-06 20:41:12,664] <docker-entrypoint> Starting unifi controller service.
[2019-02-06 20:41:12,670] <docker-entrypoint> INFO: Changing 'unifi' UID to '921' and GID to '972'
```
