### ISSUE TITLE
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by buckaroogeek** [jacobalberty/unifi-docker#170]
### Host operating system
Fedora 29

### What tag are you using
latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker run --rm --init --network unifinet --ip 192.168.110.226 -e TZ=America/Pacific -e RUNAS_UID0=false -e UNIFI_UID=$uUID -e UNIFI_GID=$uGID -v $PWD/unifi-vol:/unifi:Z -v $PWD/run:/var/run/unifi:Z --name unifi jacobalberty/unifi:latest

### What do you expect to happen?
[bgsmith@pico unifi]$ unifi.sh 
unifinet
6d7b0c34c8ea78c234219397740002f72f5be72b239ca3b1d98148b074a4ccfe
[2019-02-09 19:19:16,558] <docker-entrypoint> Cert directory found. Checking Certs
[2019-02-09 19:19:16,560] <docker-entrypoint> Cert has not changed, not updating controller.
[2019-02-09 19:19:16,563] <docker-entrypoint> Starting unifi controller service.
[2019-02-09 19:19:17,575] <docker-entrypoint> INFO: Changing 'unifi' UID to '1000' and GID to '1000'

### What actually happens?
[bgsmith@pico unifi]$ unifi.sh 
unifinet
6d7b0c34c8ea78c234219397740002f72f5be72b239ca3b1d98148b074a4ccfe
[2019-02-09 19:19:16,558] <docker-entrypoint> Cert directory found. Checking Certs
[2019-02-09 19:19:16,560] <docker-entrypoint> Cert has not changed, not updating controller.
[2019-02-09 19:19:16,563] <docker-entrypoint> Starting unifi controller service.
[2019-02-09 19:19:17,575] <docker-entrypoint> INFO: Changing 'unifi' UID to '1000' and GID to '1000'
Feb 09, 2019 7:19:25 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 09, 2019 7:19:25 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Feb 09, 2019 7:19:25 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 09, 2019 7:19:25 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Feb 09, 2019 7:19:25 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 09, 2019 7:19:25 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request

The controller seems to be working normally. I just updated to the latest version of the controller using a docker pull request.

thanks

**Comment by duaneg** [comment]
I am seeing this also.

**Comment by deluxor** [comment]
`deluxor@b0x:~$ docker run --restart=always -d -e TZ='Europe/Lisbon' -v ~/unifi:/unifi --net=host --name unifi jacobalberty/unifi`

Returns this:

> deluxor@b0x:~$ docker logs -f unifi
[2019-02-11 23:20:17,831] <docker-entrypoint> Starting unifi controller service.
[2019-02-11 23:20:17,837] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode
Feb 11, 2019 11:20:19 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 11, 2019 11:20:19 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Feb 11, 2019 11:20:19 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 11, 2019 11:20:19 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Feb 11, 2019 11:20:19 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
Feb 11, 2019 11:20:19 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry

**Comment by phroggster** [comment]
From [UBNT-MaciejC](https://community.ubnt.com/t5/UniFi-Wireless/UniFi-Network-Controller-5-10-12-Stable-Candidate-has-been/m-p/2664256/highlight/true#M363754) on the 5.10.12 stable ~~candidate~~ release thread:

> If you observe logs like this in service status on ubuntu/debian
> ```
> Feb 06 10:30:54 ubnt unifi[20868]: Feb 06, 2019 10:30:54 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
> INFO: Retrying request
> Feb 06 10:30:54 ubnt unifi[20868]: Feb 06, 2019 10:30:54 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
> INFO: I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
> Feb 06 10:30:54 ubnt unifi[20868]: Feb 06, 2019 10:30:54 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
> ```
> But finally there is
> ```
> Feb 06 10:31:05 ubnt unifi.init[20812]: ...done.
> Feb 06 10:31:05 ubnt systemd[1]: Started unifi.
> ```
> That's only cosmetic issue, not impacting controller start or informing that something went wrong, we're working on that, you don't have to worry about it !
>
> BR

**Comment by deluxor** [comment]
Hmm, sorry to desagree but the service does not start, you can't request at port 8443. Something is preventing the service to be listened.

**Comment by phroggster** [comment]
> Hmm, sorry to desagree but the service does not start, you can't request at port 8443. Something is preventing the service to be listened.

You're probably experiencing a different problem, as the log messages noted aren't fatal on their own. Check your `~/unifi/logs/server.log` file for details. Offhand, I'm going to randomly guess that it's related to host SELinux policy requiring you to add the `shared` bit on the bind mount, à la:

`docker run --restart=always -d -e TZ='Europe/Lisbon' -v ~/unifi:/unifi:z --net=host --name unifi jacobalberty/unifi` (note the lower-case Z), but there's *millions* of other possibilities.

**Comment by d-zalewski** [comment]
Having same issue running it on my Synology NAS. Apparently newer version of openjdk-jre is required

**Comment by d-zalewski** [comment]
I've tried building a new image with oracle jre 1.8-201 but it didn't help. Latest 5.10.17 has same issue and if your data were from 5.9.x you will get a message "We do not support upgrading from 5.10.17." when trying to access the web gui.

**Comment by d-zalewski** [comment]
any got latest image working?

**Comment by phroggster** [comment]
It works just fine for me on several Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64) hosts with docker-ce 5:18.09.2~3-0, containerd.io 1.2.2-3, docker/compose:1.23.2, and container versions 5.10.12, 5.10.15, 5.10.16, and (latest) 5.10.17. I get the same NON-FATAL warnings that this issue is reporting, but all of these container versions work appropriately in either of these deployment options:

`docker run -it --rm -e TZ='UTC' -v $HOME/unifitesting:/unifi:z --name testunifi -p 10.pp.qq.rr:8080:8080 -p 10.pp.qq.rr:8443:8443 -p 10.pp.qq.rr:3478:3478/udp -p 10.pp.qq.rr:10001:10001/udp jacobalberty/unifi:latest`

Or
```bash
# .env
BASH_IMGTAG=latest
MONGODB_IMGTAG=3.4
UNIFI_IMGTAG=latest

TZ=abc/def
IPADDR=10.xx.yy.zz:
UNIFI_UID=998
UNIFI_GID=998

APP_NAME=unifi
```
```yml
# docker-compose.yml
version: "3.7"
services:
  mongo:
    image: mongo:${MONGODB_IMGTAG:-3.4}
    environment:
      TZ: ${TZ:-UTC}
    networks:
      - db
    restart: always
    volumes:
      - db:/data/db/
      - type: tmpfs
        target: /data/configdb/
  controller:
    image: jacobalberty/unifi:${UNIFI_IMGTAG:-latest}
    depends_on:
      - mongo
    environment:
      BIND_PRIV: "true"
      DB_NAME: ace
      DB_URI: mongodb://mongo/ace
      JVM_MAX_THREAD_STACK_SIZE: 1280k
      RUNAS_UID0: "false"
      STATDB_URI: mongodb://mongo/ace_stat
      TZ: ${TZ:-UTC}
      UNIFI_GID: ${UNIFI_GID:-999}
      UNIFI_UID: ${UNIFI_UID:-999}
    init: true
    networks:
      - db
    ports:
      - "${IPADDR}3478:3478/udp"
      - "${IPADDR}6789:6789"
      - "${IPADDR}8080:8080"
      - "${IPADDR}8443:8443"
      - "${IPADDR}10001:10001/udp"
    restart: always
    volumes:
      - data:/unifi/data/
      - log:/unifi/log/
      - pki:/unifi/cert/
      - type: tmpfs
        target: /var/run/unifi/
      - type: tmpfs
        target: /unifi/
  logs:
    image: bash:${BASH_IMGTAG:-latest}
    command: bash -c 'tail -f /unifi/log/*'
    depends_on:
      - controller
    environment:
      TZ: ${TZ}
    network_mode: "none"
    restart: always
    volumes:
      - log:/unifi/log/:ro

volumes:
  data:
  db:
  log:
  pki:

networks:
  db:
```
