### ISSUE TITLE
Adoption continuously fails due to wrong inform ip address

### ISSUE THREAD

**Issue by tomuta** [jacobalberty/unifi-docker#192]
### Host operating system

Debian stretch

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
version: '2.2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - unifi
    restart: always
    volumes:
      - /home/unifi/db:/data/db
  controller:
    image: jacobalberty/unifi:stable
    depends_on:
      - mongo
    init: true
    networks:
      unifi:
    restart: always
    volumes:
      - /home/unifi/data:/unifi/data
      - /home/unifi/log:/unifi/log
      - /home/unifi/cert:/unifi/cert
      - /home/unifi/init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery

volumes:
  db:
  data:
  cert:
  init:

networks:
  unifi:
```

### What do you expect to happen?

Adopting devices to work

### What actually happens?

Adopting devices continuously fail

I noticed this in the logs:

> [2019-04-06T18:16:40,158] <discover> INFO  dev    -    [Try Adopt] dev[xx:xx:xx:xx:xx:xx], dev_ip=192.168.1.1, url=http://172.19.0.3:8080/inform

Notice how the inform url has the internal docker ip address. I think this is preventing the adoption of devices from working. How can I fix this so that the IP address is the same as the host?
