### ISSUE TITLE
RADIUS Certs

### ISSUE THREAD

**Issue by nessor** [jacobalberty/unifi-docker#195]
### Host operating system

Ubuntu 16.04

### What tag are you using

stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

docker-compose:

```
version: '2.2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - unifi
    restart: always
    volumes:
      - /home/unifi/database:/data/db
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - /home/unifi/data:/unifi/data
      - /home/unifi/log:/unifi/log
      - /etc/letsencrypt/live/domain:/unifi/cert
      - /home/unifi/init:/unifi/init.d
    environment:
      UNIFI_UID: 1004 # The UID from the unifi user on the system
      UNIFI_GID: 1003 # The group the UniFi service runs
      TZ: Germany/Berlin # Sets the TimeZone
      RUNAS_UID0: 'false' # To run this instance not as root set this to false
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi

    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller communication
      - "8085:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
#      - "8843:8843/tcp" # HTTPS portal redirection
#     - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*.log'
    restart: always
    volumes:
      - /home/unifi/log:/unifi/log

networks:
  unifi:
```

### What do you expect to happen?
Use Lets Enc. certs for RADIUS WPA Enterprise auth
### What actually happens?
The system still used the self-signed certs

Hey Guys,

does anybody know if it's possible to use Lets Encrypt certificates for usage in a RADIUS WPA Enterprise environment? If yes, the linked certs are not used. Because it's very hard with symbolic links and docker ([see this for example](https://stackoverflow.com/questions/38485607/mount-host-directory-with-a-symbolic-link-inside-in-docker-container/40322275#40322275) ) I used directly the Lets Encrypt unifi folder as a linked volume (as seen above). 

Love to hear from you!
-nessor
