### ISSUE TITLE
Cannot start controller since changing to non-root user - errors in log for chown

### ISSUE THREAD

**Issue by jptechnical** [jacobalberty/unifi-docker#253]
### Host operating system

macOS 

### What tag are you using

5.12 (or latest)

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

` docker-compose up -d && docker-compose logs -f `

```
docker-compose.yml
version: '3'

services:

  unifi-controller:
    container_name: unifi.controller.latest
    image: jacobalberty/unifi:5.12
    restart: always
    volumes:
      - './data/unifi:/unifi'
    ports:
      - '3478:3478/udp'
      - '10001:10001/udp'
      - '6789:6789/tcp'
      - '8080:8080/tcp'
      - '8880:8880/tcp'
      - '8443:8443/tcp'
      - '8843:8843/tcp'
    environment:
      - TZ=America/Anchorage
      - RUNAS_UID0=false
      - UNIFI_UID=999
      - UNIFI_GID=999
    labels:
      - 'unifi-controller'

```
### What do you expect to happen?

Container should run like it did before changing to non-root.

### What actually happens?

Logs are full of errors for ownership and access issues. 
```
 [2019-11-05 17:22:54,924] <docker-entrypoint> Using openssl to prepare certificate...
unifi.controller.latest | awk: cannot open /unifi/cert/chain.pem (Permission denied)
unifi.controller.latest | Can't open /unifi/cert/privkey.pem for reading, Permission denied 
```

```
 chown: changing ownership of '/unifi/log/mongod.log': Operation not permitted 
```

``` 
$ll data/unifi/
Permissions Size User Date Modified Git Name
drwxr-xr-x     - 999  21 Jan  9:34   -I cert
drwxr-xr-x     - 999   2 May 18:17   -I data
drwxr-xr-x     - 999   4 Nov 17:21   -I log
drwxr-xr-x     - 999   5 Nov  7:16   -I run
```

 I copied directories from production server for folder structure, ran the container as root and no errors. I ran ` chown -R 999:999 data ` to set ownership of the directories in the volume. No chmod was done to the files and folders. Added the three ENVs and ran the container and it fails to access the files.
