### ISSUE TITLE
Additional docker volume is created

### ISSUE THREAD

**Issue by varac** [jacobalberty/unifi-docker#282]
### Host operating system

`Debian buster`

### What tag are you using

`latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
version: "3"

services:

  unifi:
    image: jacobalberty/unifi
    environment:
      TZ: 'Europe/Berlin'
      UNIFI_HTTPS_PORT: '443'
    container_name: unifi
    restart: always
    network_mode: "bridge"
    ports:
      - "10.27.192.10:80:8080/tcp"
      - "10.27.192.10:8080:8080/tcp"
      - "10.27.192.10:443:443/tcp"
      - "10.27.192.10:8443:443/tcp"
      - "10.27.192.10:3478:3478/udp"
      - "10.27.192.10:10001:10001/udp"
    volumes:
      - /srv/docker/unifi:/unifi
```

### What do you expect to happen?

No additional docker volume is added upon `docker-compose up`

### What actually happens?

After `docker-compose up` there's a new docker volume created with only 2 actual files:

```
root@brix:/var/lib/docker/volumes# docker volume ls
DRIVER              VOLUME NAME
local               4da3ae4f773499dda93e023c62e4b2d8055617076947c54ef911cd157bfc18ee

root@brix:/var/lib/docker/volumes# find 4da3ae4f773499dda93e023c62e4b2d8055617076947c54ef911cd157bfc18ee/
4da3ae4f773499dda93e023c62e4b2d8055617076947c54ef911cd157bfc18ee/
4da3ae4f773499dda93e023c62e4b2d8055617076947c54ef911cd157bfc18ee/_data
4da3ae4f773499dda93e023c62e4b2d8055617076947c54ef911cd157bfc18ee/_data/work
4da3ae4f773499dda93e023c62e4b2d8055617076947c54ef911cd157bfc18ee/_data/work/ROOT
4da3ae4f773499dda93e023c62e4b2d8055617076947c54ef911cd157bfc18ee/_data/mongodb-27117.sock
4da3ae4f773499dda93e023c62e4b2d8055617076947c54ef911cd157bfc18ee/_data/update.json
```
