### ISSUE TITLE
Controller constantly resolving it's own hostname?

### ISSUE THREAD

**Issue by adrianmace** [jacobalberty/unifi-docker#294]
### Host operating system

Ubuntu Server 19.04

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
 unifi:
    container_name: EX-UNIFI-01
    restart: always
    image: jacobalberty/unifi:latest
    hostname: unifi
    ports:
      - "172.20.22.4:3478:3478/udp"
      - "172.20.22.4:10001:10001/udp"
      - "172.20.22.4:8080:8080/tcp"
      - "172.20.22.4:8081:8081/tcp"
      - "172.20.22.4:8880:8880/tcp"
      - "172.20.22.4:8843:8843/tcp"
      - "172.20.22.4:6789:6789/tcp"
    volumes:
      - ./volumes/EX-UNIFI-01:/unifi
    environment:
      - TZ=Australia/Melbourne
    labels:
      - "traefik.enable=true"
      - "traefik.tags=frontend"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.admin.backend=unifi"
      - "traefik.admin.frontend.rule=Host:unifi.in.domain.net"
      - "traefik.admin.port=8443"
      - "traefik.admin.protocol=https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=in.domain.net"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
```

### What do you expect to happen?

Pi-Hole Statistics show a normal amount of requests to `unifi.in.domain.net`.

### What actually happens?

Pi-Hole Statistics show that `unifi.in.domain.net` is being resolved once every 5 seconds.
