### ISSUE TITLE
"Try New Settings" - 400 error after upgrade.

### ISSUE THREAD

**Issue by brontide** [jacobalberty/unifi-docker#299]
### Host operating system

Docker CE 19.03.5 on Fedora 30

### Controller version

`5.12.66.0`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
version: '2'
services:
 unifi-controller:
   image: jacobalberty/unifi:stable
   restart: always
   volumes:
     - ./unifi:/unifi
   networks:
     - web
     - default
   expose:
     - "8080"
   ports:
     - "3478:3478/udp"
     - "10001:10001/udp"
     - "6789:6789/tcp"
     - "8080:8080/tcp"
     - "8880:8880/tcp"
     - "8443:8443/tcp"
     - "8843:8843/tcp"
   environment:
     - TZ=America/New_York
     - RUNAS_UID0=false
     - UNIFI_UID=1000
     - UNIFI_GID=1000 
   labels:
     - "traefik.docker.network=web"
     - "traefik.backend=unifi-controller"
     - "traefik.frontend.rule=Host:unifi.mydomain.com"
     - "traefik.enable=true"
     - "traefik.port=8443"
     - "traefik.protocol=https"
#   network_mode: "host"

networks:
  web:
    external: true
```

### What do you expect to happen?

I had completed a `docker-compose pull && docker-compose up -d` and was browsing the settings I was not expecting a 400 error.

### What actually happens?

When clicking on "Try New Settings" I was put into a 400 error that I was unable to get out of.  Every time I selected settings it would fail.  The URL had the following string in it `dynamic.ufsdn` and then an ID, looked like a mongo id.

### Fix

I had to clear out the application information in the browser, cookies, sessiondb, ... and then log in again and I was able to use settings again including new and classic settings.  I'm unable to reproduce the issue after clearing the session data but I wanted to open and document the issue in case anyone else ran into it.  You can feel free to close this issue.
