### ISSUE TITLE
High disk activity

### ISSUE THREAD

**Issue by anoxi** [jacobalberty/unifi-docker#300]
### Host operating system

Debian 10.3

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

version: '2.2'
services:
  mongo:
    image: mongo:3.4
    networks:
      - unifi
    restart: always
    volumes:
      - ./db:/data/db
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - ./data:/unifi/data
      - ./log:/unifi/log
      - ./cert:/unifi/cert
      - ./init:/unifi/init.d
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    depends_on:
      - controller
    command: bash -c 'tail -f /unifi/log/*.log'
    restart: always
    volumes:
      - ./log:/unifi/log

networks:
  unifi:

### What do you expect to happen?
Disk activity is reasonable

### What actually happens?

Constant high disk activity.

Is there anything i can tune to reduce disk activity? I have already set all logging options to the lowest level.

**Comment by IngmarStein** [comment]
I'm experiencing the same issue and it renders running a container using this image infeasible on my Synology DS216+II. Here's the snipped from my docker-compose file:
```
  unifi:
    image: jacobalberty/unifi:latest
    init: true
    container_name: unifi
    network_mode: host
    environment:
      BIND_PRIV: "false"
      RUNAS_UID0: "false"
      UNIFI_GID: "100"
      UNIFI_UID: "1026"
      TZ: "Europe/Zurich"
    volumes:
      - type: bind
        source: /volume1/docker/unifi
        target: /unifi
    restart: unless-stopped
```

**Comment by IngmarStein** [comment]
Setting `unifi.db.nojournal=true` and `unifi.db.extraargs=--quiet` improves the situation for me (load to more spiky now and much lower on average than the constant 100% without this change), but those settings seem to be reset to default values after the container has started up once.

**Comment by anoxi** [comment]
Thanks for the response. I set these options in data/system.properties and i guess it should influence the mongo database settings. I also suspected the mongo database for the high disk activity. How can you check that these settings have been applied? Unfortunately I cannot confirm that the disk activity has decreased significantly.

**Comment by IngmarStein** [comment]
Have a look at the command line arguments passed to `mongod`, e.g. using `docker top ${unifi_container_name}`. It should look like this:
```
bin/mongod --dbpath /usr/lib/unifi/data/db --port 27117 --unixSocketPrefix /usr/lib/unifi/run --logappend --logpath /usr/lib/unifi/logs/mongod.log --quiet --bind_ip 127.0.0.1 --nojournal
```
I let it run like this for a day and load has not gone up since.

**Comment by IngmarStein** [comment]
I just noticed that you use an external mongo container. In that case, setting the unifi.db.* parameters has no effect.
You'd have to pass them like this in your docker-compose file (see https://hub.docker.com/_/mongo):
```
services:
  mongo:
    image: mongo
    command: --quiet --nojournal
```
