### ISSUE TITLE
Proper watchtower format in docker-compose.yml?

### ISSUE THREAD

**Issue by wazlecracker** [jacobalberty/unifi-docker#309]
### Host operating system

Manjaro 20

### What tag are you using

`latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
version: '2'
services:
 unifi-controller:
   container_name: unifi.controller
   image: jacobalberty/unifi:latest
   restart: unless-stopped
   volumes:
     - './data/lib:/var/lib/unifi'
     - './data/log:/var/log/unifi'
     - './data/run:/var/run/unifi'
   ports:
     - '22:22/tcp'
     - '3478:3478/udp'
     - '6789:6789/tcp'
     - '8080:8080/tcp'
     - '8880:8880/tcp'
     - '8443:8443/tcp'
     - '8843:8843/tcp'
     - '10001:10001/udp'
   environment:
     - TZ=America/New_York
   labels:
     - 'unifi-controller'
   network_mode: "bridge"
 watchtower:
   container_name: watchtower
   image: containrrr/watchtower:latest
   restart: unless-stopped
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./watchtower/config.json:/config.json
   command: --cleanup
   labels:
     - 'watchtower'
```

### What do you expect to happen?
Watchtower to automatically update the unifi controller.
### What actually happens?
I had to manually update to the latest image with `docker-compose pull && docker-compose up -d`.
