### ISSUE TITLE
Setting UNIFI_HTTP_PORT once breaks the default configuration

### ISSUE THREAD

**Issue by filoozom** [jacobalberty/unifi-docker#328]
### Host operating system

Ubuntu

### What tag are you using

`stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
version: '3.7'
services:
  controller:
    image: "jacobalberty/unifi:stable"
    environment:
      UNIFI_HTTP_PORT: 80
```

then, go back to the default configuration:

```
version: '3.7'
services:
  controller:
    image: "jacobalberty/unifi:stable"
```

### What do you expect to happen?

The HTTP port should return to its default, basically it should be unset from `system.properties`. Same for `UNIFI_HTTPS_PORT`.

### What actually happens?

The previous configuration stays in `system.properties` because of the `[[ -z ]]` check:

```
if ! [[ -z "$UNIFI_HTTP_PORT" ]]; then
  settings["unifi.http.port"]="$UNIFI_HTTP_PORT"
fi
```

I don't know if there's a reason for that check, but I'm guessing that removing it should do the trick.
