### ISSUE TITLE
TZ environment variable seems to be ignored

### ISSUE THREAD

**Issue by arikalish** [jacobalberty/unifi-docker#334]
### Host operating system

Synology DSM 6.2.3-25426 on DS918+

### What tag are you using

`beta`

Of note: This started happening after the `beta-3.6` branch was merged into `beta`.

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

`docker compose up -d` with:

```
version: "2"
services:
  unifi:
    container_name: unifi
    hostname: unifi
    image: jacobalberty/unifi:beta
    cpu_shares: 50
    environment:
      - "BIND_PRIV=true"
      - "RUNAS_UID0=false"
      - "UNIFI_GID=65538"
      - "UNIFI_UID=1033"
      - "TZ=America/New_York"
      - "PKGURL=https://dl.ui.com/unifi/5.14.17-254554c8a7/unifi_sysvinit_all.deb"
    logging:
      driver: db
      options: {}
    dns: 
      - 192.168.15.2
      - 192.168.15.4
    dns_search:
      - "local"
    networks:
      netservices:
        ipv4_address: 192.168.15.254
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /volume1/dockerconfigs/unifi:/unifi:rw
    working_dir: /unifi
```

### What do you expect to happen?
Container is created and automatically configures `tzdata` based on the provided `TZ` environment variable.

### What actually happens?
`tzdata` asks for configuration during container creation:

```
Setting up tzdata (2020a-0ubuntu0.18.04) ...                                                                   
debconf: unable to initialize frontend: Dialog                                                                 
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/shar
e/perl5/Debconf/FrontEnd/Dialog.pm line 76.)                                                                   
debconf: falling back to frontend: Readline                                                                    
debconf: unable to initialize frontend: Readline                                                               
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC conta
ins: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-g
nu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_per
l /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)               
debconf: falling back to frontend: Teletype                                                                    
Configuring tzdata                                                                                             
------------------                                                                                             
                                                                                                               
Please select the geographic area in which you live. Subsequent configuration questions will narrow this down  
by presenting a list of cities, representing the time zones in which they are located.                         
                                                                                                               
  1. Africa   3. Antarctica  5. Arctic  7. Atlantic  9. Indian    11. SystemV  13. Etc                         
  2. America  4. Australia   6. Asia    8. Europe    10. Pacific  12. US                                       
Geographic area:
```

Manually entering the appropriate area and city in an attached terminal allows the container to finish initialization and then everything works fine.

I've tried a few variants of the `"TZ=America/New_York"` line and none have worked. When attaching a terminal to the container at the time it's asking for the above configuration shows that it's set correctly:

```
root@unifi:/unifi# echo $TZ                                                                                    
America/New_York
```

Other containers on the same machine have no issue with time zones provided by `docker-compose` in the same manner.


Any guidance is appreciated.
