### ISSUE TITLE
UniFi controller + Traefik v1.7: cannot proxy to Controller GUI

### ISSUE THREAD

**Issue by Gitoffomalawn** [jacobalberty/unifi-docker#338]
### Host operating system

Arch Linux, running `5.4.50-1-lts` kernel

### What tag are you using

`stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

**docker-compose.yml:**
```
version: "3.8"
services:
  traefik:
    hostname: traefik
    image: traefik:v1.7.16
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - test
    ports:
      - "80:80"
      - "443:443"
      - "8085:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=test"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/traefik:/etc/traefik
      - ${USERDIR}/shared:/shared
      - ${USERDIR}/traefik/certs:/certs

  controller:
    image: "jacobalberty/unifi:stable"
    container_name: unifi_controller
    init: true
    networks:
      - test
    restart: always
    volumes:
      - ./unifi/dir:/unifi
      - ./unifi/data:/unifi/data
      - ./unifi/log:/unifi/log
      - ./unifi/cert:/unifi/cert
      - ./unifi/init:/unifi/init.d
      - ./unifi/run:/var/run/unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    labels:
      - "traefik.enable=true"
      - "traefik.backend=unifi"
      - "traefik.frontend.rule=Host:unifi.${DOMAINNAME}"
      - "traefik.port=8443"
      - "traefik.docker.network=test"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"

networks:
  test:
```

**traefik.toml:**
```
logLevel = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
defaultEntryPoints = ["http", "https"]
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
      users = ["admin:some_password_hash"]
  [entryPoints.http]
    address = ":80"
#      [entryPoints.http.redirect]
#        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "/certs/test.lan.crt"
    keyFile = "/certs/test.lan.key"

[api]
entrypoint="dashboard"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "test.lan"
watch = true
network = "test"
# This will hide all docker containers that don't have explicitly
# set label to "enable"
exposedbydefault = false
```

### What do you expect to happen?

When I got to `unifi.test.lan` (I have DNS set up so that `*.test.lan` points to the host running the above containers), I expect to land on the Controller GUI page for setup. 

### What actually happens?
I get the following error, even though I put self a self-signed certificate for `unifi.test.lan` in the `./unifi/cert` directory as per the instructions in this repository:
```
Bad Request
This combination of host and port requires TLS.
```
Strange thing is, in my search for a solution I tried substituting the `"traefik.port=8443"` environment variable with `"traefik.port=8080"`, which got me to the GUI for configuration. However, this didn't let me save the config, presumably because it couldn't redirect to port 8443. This, and the error above, leads me to think something's up with the redirection to port 8443. With both of these variations using `https://unifi.test.lan:8443` leads me to the GUI and allows me to save at the end, no problem. However, having to tag on the port number at the end there kind of defeats the purpose of having a reverse proxy in the first place.

Curiously, when using the `"traefik.port=8080"` and navigating to `https://unifi.test.lan`, the GUI uses the self-signed certificate for `*.test.lan` that is confogured for Traefik. However, in both cases, navigating to `https://unifi.test.lan:8443` shows the certificate by Ubiquiti being used. This could indicate a certificate issue, but the information on this repository isn't enough for me to troubleshoot any such issues.

I have also tried changing the `traefik.toml` config to variations with and without the `InsecureSkipVerify = true` argument, seeing as I found many people with similar problems who have found this to be a solution that works. It doesn't, in my case.
