### ISSUE TITLE
Failed startup due to existing symlink after `docker-compose.yml` changes

### ISSUE THREAD

**Issue by fongd** [jacobalberty/unifi-docker#366]
The latest `beta` tag fails to start the controller service if I make a change to a running UniFi container. It seems like a symlink at `/usr/lib/unifi/run/unifi` tries to get created but fails if it already exists, preventing startup of the controller service.

I can reproduce this with an already running controller by changing one of the service's parameters in my `docker-compose.yml` file, running `docker-compose up -d` to apply the changes, then waiting for the controller to come up.

I think there needs to be a check to prevent the symlink from getting created if it already exists or maybe just delete the existing one before the new one gets created.

### Host operating system

Ubuntu 20.04.1 LTS

### What tag are you using

`beta`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
unifi:
  image: jacobalberty/unifi:beta
  container_name: unifi
  volumes:
    - /opt/dockerdata/unifi:/unifi
  networks:
    net_lan:
  environment:
    - TZ=${TZ}
    - RUNAS_UID0=false
    - UNIFI_UID=1003
    - UNIFI_GID=1003
    - PKGURL=https://dl.ui.com/unifi/5.14.23-70ddb4015a/unifi_sysvinit_all.deb
  restart: unless-stopped
```

### What do you expect to happen?

UniFi should start up :)

### What actually happens?

UniFi fails to start with the following error:

```
…
ln: failed to create symbolic link '/usr/lib/unifi/run/unifi': File exists
[2020-10-17 12:06:29,620] <docker-entrypoint> Starting unifi controller service.
```
