### ISSUE TITLE
6.0.28 now requires root for mongodb

### ISSUE THREAD

**Issue by jtackaberry** [jacobalberty/unifi-docker#371]
I run the controller as a non-root user, and this has been working fine since I originally deployed it earlier this year, including with 6.0.23, but as of 6.0.28, mongodb refuses to start:

```
2020-10-20T17:36:20.790+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2020-10-20T17:36:20.794+0000 I CONTROL  [main] ERROR: Cannot write pid file to /usr/lib/unifi/run/mongod.pid: Permission denied
```

`/usr/lib/unifi/run` is a symlink to `/var/run/unifi`.

On 6.0.23:

```
$ ls -ld /var/run/unifi
drwxrwsrwx 3 root 2000 4096 Oct 20 17:37 /var/run/unifi
```

And on 6.0.28:

```
$ ls -ld /var/run/unifi/
drwxr-xr-x 2 root root 4096 Oct 20 17:41 /var/run/unifi/
```

So this requires mongodb to run as root.

I am running the container under Kubernetes, with a `securityContext` stanza defining a non-root uid/gid:

```yaml
      securityContext:
        runAsUser: 10011
        runAsGroup: 10011
        supplementalGroups: [10011]
```
