### ISSUE TITLE
Controller on beta starts but requests time out

### ISSUE THREAD

**Issue by fongd** [jacobalberty/unifi-docker#374]
### Host operating system

Ubuntu 20.04.1 LTS

### What tag are you using

`beta`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
unifi:
  image: jacobalberty/unifi:beta
  container_name: unifi
  volumes:
    - /opt/dockerdata/unifi:/unifi
  networks:
    default:
  ports:
    - "3478:3478/udp"  # STUN service
    - "6789:6789/tcp"  # speedtest
    - "8080:8080/tcp"  # device command/control
    - "8443:8443/tcp"  # web interface + API
    - "8843:8843/tcp"  # HTTPS portal redirection
#      - "8880:8880/tcp"  # HTTP portal
    - "10001:10001/udp"  # UBNT discovery
  environment:
    - TZ=${TZ}
    - RUNAS_UID0=false
    - UNIFI_UID=1003
    - UNIFI_GID=1003
    - PKGURL=https://dl.ui.com/unifi/5.14.23-70ddb4015a/unifi_sysvinit_all.deb
  restart: unless-stopped
```

### What actually happens?

The container's log indicates that the service has started up but attempts to access the container at http://192.168.8.15:8080/inform eventually time out. Going to https://192.168.8.15:8443 (the controller URL) in Safari immediately returns a "Safari can't connect to the server" error suggesting that nothing is listening on 8443. This broke at some point in the last couple of hours after Ouroboros reported a couple of updates to this container.

Here are some possibly relevant troubleshooting points:

Docker logs:

```
…
Setting up mongodb-clients (1:3.6.3-0ubuntu1.1) ...
Setting up mongodb-server (1:3.6.3-0ubuntu1.1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up binutils (2.30-21ubuntu1~18.04.4) ...
Setting up unifi (5.14.23-13880-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
[2020-10-20 20:05:14,180] <docker-entrypoint> Starting unifi controller service.
[2020-10-20 20:05:15,188] <docker-entrypoint> INFO: Changing 'unifi' UID to '1003' and GID to '1003'
```

From the host showing the uid/gid the container is running as:

```
[fong@Enterprise docker ]$ id unifi
uid=1003(unifi) gid=1003(unifi) groups=1003(unifi)
```

Permissions on the mounted volume as seen on the host:

```
[fong@Enterprise docker ]$ sudo ls -l /opt/dockerdata/unifi     
total 18
drwxr-xr-x 2 unifi unifi  2 Sep 23 15:56 cert
drwxr-xr-x 7 unifi unifi 13 Oct 20 12:31 data
drwxr-xr-x 3 unifi unifi  8 Sep 23 15:57 log
```
