### ISSUE TITLE
config.gateway.json not read after update to stable-5

### ISSUE THREAD

**Issue by buckaroogeek** [jacobalberty/unifi-docker#400]
I updated the controller using docker-compose following the same steps I have used many times before. For some reason the config.gateway.json file is no longer being processed so that the hostnames defined in the file do not resolve on the network. I have restarted the container several times with the same result. Thanks for any tips on resolving. See also https://github.com/jacobalberty/unifi-docker/issues/399#issue-772423200 for a co-occuring issue that is possibly related.

### Host operating system

Synology DSM 6

### What tag are you using

stable-5

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
sudo docker-compose pull
sudo docker-compose  up -d unifi

```
Partial docker-compose.yaml file:

```
  unifi:
    image: "jacobalberty/unifi:stable-5"
    container_name: SageCreek-Unifi-Controller
    hostname: unifi2
    domainname: lan
    mac_address: d0:ca:ab:cd:ef:ac
    depends_on:
      - mongo
    init: true
    networks:
      macvlan1:
        ipv4_address: 192.168.110.216
    restart: unless-stopped
    volumes:
#      - /volume1/docker/unifi:/unifi
      - /volume1/docker/unifi2/data:/unifi/data
      - /volume1/docker/unifi2/log:/unifi/log
      - /volume1/docker/unifi2/cert:/unifi/cert
      - /volume1/docker/unifi2/init.d:/unifi/init.d
      - /volume1/docker/unifi2/run:/var/run/unifi
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      TZ: America/Pacific
      UNIFI_HTTP_PORT: 80
      UNIFI_HTTPS_PORT: 443
      # RUNAS_UID0: false
      # UNIFI_UID: 1029
      # UNIFI_GID: 65537
    ports:
      - "1900/udp"    # L2 discovery
      - "3478/udp"    # STUN
      - "6789/tcp"    # Speed test
      - "80/tcp"      # Device/ controller comm.
      - "443/tcp"     # Controller GUI/API as seen in a web browser
      - "8880/tcp"    # HTTP portal redirection
      - "8843/tcp"    # HTTPS portal redirection
      - "10001/udp"   # AP discovery
      - "27117/tcp"   # DB communications

```
### What do you expect to happen?

config.gateway.json to be processed as usual. See also https://github.com/jacobalberty/unifi-docker/issues/399#issue-772423200 for a related problem that occured after the update. 

### What actually happens?
Unifi controller launches and works. Host names defined in config.gateway.json not resolving (e.h. unifi2.lan for controller).
