### ISSUE TITLE
Feature: Include jmx_exporter for monitoring

### ISSUE THREAD

**Issue by SuperQ** [jacobalberty/unifi-docker#408]
### Host operating system

QNAP container station

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Using example docker-compose.

### Feature idea

Bundle the [jmx_exporter](https://github.com/prometheus/jmx_exporter) with the docker image to allow direct monitoring of the controller's java process.

To prototype this, I've configured the `-javaagent` by including it in `/unifi/jmx_exproter` and then running with this env var:

```sh
JVM_EXTRA_OPTS='-javaagent:/unifi/jmx_exporter/jmx_prometheus_javaagent-0.14.0.jar=9560:/unifi/jmx_exporter/config.yml'
```

This allows me to gather monitoring data directly from the controller's Java process via `curl -s http://localhost:9560/metrics`.

This is my current jmx_exporter config.yml, based on the data I found in JMX and an example Tomcat config.

```yaml
---
lowercaseOutputLabelNames: true
lowercaseOutputName: true
rules:
- pattern: 'Tomcat<type=GlobalRequestProcessor, name=\"(\w+-\w+)-(\d+)\"><>(\w+):'
  name: tomcat_$3_total
  labels:
    port: "$2"
    protocol: "$1"
  help: Tomcat global $3
  type: COUNTER
- pattern: 'Tomcat<j2eeType=Servlet, WebModule=//([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), name=([-a-zA-Z0-9+/$%~_-|!.]*), J2EEApplication=none, J2EEServer=none><>(requestCount|maxTime|processingTime|errorCount):'
  name: tomcat_servlet_$3_total
  labels:
    module: "$1"
    servlet: "$2"
  help: Tomcat servlet $3 total
  type: COUNTER
- pattern: 'Tomcat<type=ThreadPool, name="(\w+-\w+)-(\d+)"><>(currentThreadCount|currentThreadsBusy|keepAliveCount|pollerThreadCount|connectionCount):'
  name: tomcat_threadpool_$3
  labels:
    port: "$2"
    protocol: "$1"
  help: Tomcat threadpool $3
  type: GAUGE
- pattern: 'Tomcat<type=Manager, host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), context=([-a-zA-Z0-9+/$%~_-|!.]*)><>(processingTime|sessionCounter|rejectedSessions|expiredSessions):'
  name: tomcat_session_$3_total
  labels:
    context: "$2"
    host: "$1"
  help: Tomcat session $3 total
  type: COUNTER
- pattern: 'org.mongodb.driver.*'
- pattern: 'com.ubnt.*'
```
