### ISSUE TITLE
Startup failed: We do not support upgrading from 6.2.23

### ISSUE THREAD

**Issue by tomuta** [jacobalberty/unifi-docker#444]
### Host operating system

Debian buster

### What tag are you using

stable-6

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
version: '2.2'
services:
  controller:
    image: jacobalberty/unifi:stable-6
    init: true
    networks:
      - unifi
    restart: always
    volumes:
       - /home/unifi/unifi:/unifi
    environment:
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
      - "27117:27117/tcp" # mongodb
    networks:
      vpcbr:
        ipv4_address: 172.16.1.2

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.1.0/24
volumes:
  unifi:
```

### What do you expect to happen?

Controller page should show and work as usual

### What actually happens?

Trying to access the controller web page shows this:
```
UniFi Controller startup failed

We do not support upgrading from 6.2.23.
```

I'm not sure what exact version I was on prior to pulling from this tag. I tried downgrading by pulling tag 6.1.71, even 6.0.23 but that also didn't help. I regularly pull the latest and this is the first time I've had a problem.

How can I recover from this?
