### ISSUE TITLE
synology dsm 7 websocket error

### ISSUE THREAD

**Issue by rickyjoy** [jacobalberty/unifi-docker#456]
### Host operating system

synology dsm 7, ds 718+

### What tag are you using

6.2.26

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Note: A screenshot of your configuration page if using a gui is acceptable

When the system was updated to dsm7, the unifi controller shows websocket error once login in. Any setting was not changed in docker or in the unifi controller.

Is there any idea?

**Comment by buckaroogeek** [comment]
Perhaps a firewall setting?

**Comment by TheRijn** [comment]
I have no problems on my DS720+ with DSM7. My config is:
```yaml
version: '3'
services:
  unifi:
    image: "jacobalberty/unifi:latest"
    container_name: unifi
    restart: always
    volumes:
      - /volume2/docker/unifi/unifi:/unifi
    network_mode: "host"
    environment:
      - BIND_PRIV=false
      - RUNAS_UID0=false
      - TZ=Europe/Amsterdam
```
