### ISSUE TITLE
restore conf via backup file 

### ISSUE THREAD

**Issue by empereira** [jacobalberty/unifi-docker#460]
### Host operating system

`debian 10`

### What tag are you using

`v6`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```
version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    networks:
      - unifi
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./db:/data/db
  controller:
    image: jacobalberty/unifi:v6
    container_name: controller
    hostname: controller
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - dir:/unifi
      - log:/unifi/log
      - ./backup:/unifi/data/backup
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      TZ: America/Sao_Paulo
    ports:
      - "3478:3478/udp"   # STUN
      - "6789:6789/tcp"   # Speed test
      - "8080:8080/tcp"   # Device/ controller comm.
      - "8443:8443/tcp"   # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp"   # HTTP portal redirection
      - "8843:8843/tcp"   # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    container_name: logs
    hostname: logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - log:/unifi/log

volumes:
  log:
  dir:

networks:
  unifi:

```
### What do you expect to happen?

That after restoring the settings, I can use it via docker with the settings I had in a virtualized version.

### What actually happens?
The error below is occurring.

`Caused by: java.lang.IllegalArgumentException: /usr/lib/unifi/data/backup/6.2.25.unf does not exist`

As I figure out, the old configuration has the backup folder in the `/usr/lib/unifi/data/backup` path and via docker it is in the `/unifi/backup` path.

Maybe this is the problem? If so, how can I work around it?
