### ISSUE TITLE
Update Mongo DB

### ISSUE THREAD

**Issue by jacobalberty** [jacobalberty/unifi-docker#527]
As of right now Unifi supports up to Mongo DB 3.6, we are still on 3.4 for AMD64/ARM64 and 3.2 for ARM32.

At the very least we need to move Mongo DB to 3.6 for AMD64 or ARM64

This does not appear to require any changes to our base image.

If possible we should build Mongo DB 3.6 for ARM32 so it can upgrade as well.

**Comment by jasonmp85** [comment]
I was just looking into this, as I was wanting to move away from standalone use myself, but… upstream seem to (in their `deb` package) restrict Mongo as follows…

```
mongodb-server (>= 2.4.10) | mongodb-10gen (>= 2.4.14) | mongodb-org-server (>= 2.6.0),
mongodb-server (<< 1:4.0.0) | mongodb-10gen (<< 4.0.0) | mongodb-org-server (<< 4.0.0),
```

Mongo's own [lifecycle policy](https://www.mongodb.com/support-policy/lifecycles) reflects that the 3.6 line was EoL'd in April 2021, which is also reflected by the "supported tags" in the official Docker image only going back to some `4.x` release or other.

Shouldn't _upstream_ be improving their own product baseline? It's been over a year since 3.6 has fallen out of any support.

**Comment by jhenstridge** [comment]
@jasonmp85: it seems likely that they're intentionally picking the earlier versions to avoid the MongoDB license change (AGPL3 to SSPL).

**Comment by jokay** [comment]
@jacobalberty given they state as requirement *"MongoDB 3.2 or later"* why doesn't it work with an external [MongoDB 6.0.x](https://hub.docker.com/layers/library/mongo/6.0/images/sha256-e0b1614551474ee2f3c3ef7c9706b5e19f2107aa36b73c910522af9fa8eb756e?context=explore)?

![image](https://user-images.githubusercontent.com/18613935/198028133-66fba1f3-7ec8-4c35-9e8d-5077d432f51d.png)

Is there any limitation from your Docker image setup?

**Comment by jokay** [comment]
Why not making your lives easier and decouple the dependencies by having two separate containers, one for the **app** and one for the **database**?

```yml
services:
  app:
    image: jacobalberty/unifi:v7.3.83
    ports:
      - 3478:3478/udp
      - 6789:6789
      - 8080:8080
      - 10001:10001/udp
    volumes:
      - ./data/app:/unifi/data
      - ./data/log:/unifi/log
    environment:
      - RUNAS_UID0=false
      - UNIFI_UID=999
      - UNIFI_GID=999
      - LOTSOFDEVICES=true
      - DB_URI=mongodb://unifi:{my-mongodb-pw}@db/unifi?authSource=admin
      - STATDB_URI=mongodb://unifi:{my-mongodb-pw}@db/unifi_stat?authSource=admin
      - DB_NAME=unifi
    networks:
      - default
    ports:
      - 8443:8443

  db:
    image: mongo:3.6.23
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=unifi
      - MONGO_INITDB_ROOT_PASSWORD={my-mongodb-pw}
      - MONGO_INITDB_DATABASE=unifi
    networks:
      - default

networks:
  default:
```
