### ISSUE TITLE
Devices cannot conntect to UniFi OS Console’s internal STUN server on port 3478 in network mode 'host'

### ISSUE THREAD

**Issue by Th3S4mur41** [jacobalberty/unifi-docker#531]
### Operating system

QNAP 5.0.0.1858 Build 20211119

### UniFi Tag

stable

### Docker run

docker compose (see description)

### Bug description

Docker compose:
```
version: '3'
services:
  unifi-controller:
    image: jacobalberty/unifi
    container_name: unifi-controller
    #command: unifi --user unifi
    restart: unless-stopped
    environment:
      - PUID=911
      - PGID=911
      - TZ=Europe/Brussels
      - UNIFI_HTTP_PORT=8080
      - UNIFI_HTTPS_PORT=8443
      - PORTAL_HTTP_PORT=8888 # default 80
      - PORTAL_HTTPS_PORT=8843
      - RUNAS_UID0=false
    volumes:
      - /share/Apps/unifi-controller/data:/unifi/data
      - /share/Apps/unifi-controller/logs:/unifi/log
      - /share/Apps/unifi-controller/run:/var/run/unifi
      - /share/Apps/cert:/unifi/cert
    network_mode: "host"
```

All devices are reporting the following error:

> This device cannot connect to your UniFi OS Console’s internal STUN server. Please check Port 3478, then see  for instructions on how to verify STUN server connectivity.

There is no errors in the logs indicating any issues with port 3478 or STUN (there is no info about it either).

Netstat shows java process listening on this port:
`udp        0      0 0.0.0.0:3478            0.0.0.0:*                           10600/java`

Any hint on how to fix the issue?
