### ISSUE TITLE
Admin password no longer works after update to v7.0.23

### ISSUE THREAD

**Issue by neilenns** [jacobalberty/unifi-docker#532]
### Operating system

Windows 10

### UniFi Tag

latest

### Docker run

```
version: "2.3"
services:
  mongo:
    image: mongo:3.6
    container_name: unifi_mongo
    networks:
      - unifi
    restart: always
    volumes:
      - ./db:/data/db
      - ./dbcfg:/data/configdb
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: unifi_controller
    depends_on:
      - mongo
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - ./dir:/unifi
      - ./data:/unifi/data
      - ./log:/unifi/log
      - ./cert:/unifi/cert
      - ./init:/unifi/init.d
      - ./run:/var/run/unifi
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      TZ: Americas/Los_Angeles
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  logs:
    image: bash
    container_name: unifi_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - ./log:/unifi/log

networks:
  unifi: null
```

### Bug description

I ran a simple `docker compose pull` to update to the latest version of the Docker images and after the system came back up I can no longer log into the Unifi controller with my admin account.

I've tried the various solutions online for connecting to the mongo db (by adding port 27017 to the docker compose file for the mongodb image), but the tables all seem to be empty.

I'm completely stuck and unable to access my controller now. Any suggestions for how I can either roll back or get access again?
