### ISSUE TITLE
Possibility to choose Unifi verision to install by ENV variable?

### ISSUE THREAD

**Issue by timokli** [jacobalberty/unifi-docker#60]
Hi, could you change the dockerfile in a way so its possible to choose the installation verison of Unifi by ENV variable? For example just check if there is the ENV "PKGURL" configured, if not, then fallback to latest stable. Or is this already possible?

**Comment by jacobalberty** [comment]
If you're using docker-compose this is easy enough with the beta branch.

```
        build:
         context: https://github.com/jacobalberty/unifi-docker.git#beta
         args:
          PKGURL: https://dl.ubnt.com/unifi/5.5.20/unifi_sysvinit_all.deb
```

PKGURL is the full path to whatever version you'd like to install, it'll then pull the repo and build the image with whatever unifi package you put in PKGURL
