### ISSUE TITLE
Reducing disk-writes to a minimum - Further MongoDB configurations

### ISSUE THREAD

**Issue by BlackEdder0815** [jacobalberty/unifi-docker#617]
Hi,
I've installed your container on my raspi and it work out quite well.
I monitored the writings from the container and I'm wondering for options to reduce the writing further.
Maybe there is an option to point to an own mongodb.conf file to tune mongo-db individually? 
I personally would like to deactivate the diagnosticDataCollection and to increase the sync-period up to 10 mins. As the collected data is just "statistical" data and a loss in case of power off would be not so critical. And also, my system is behind a battery buffer.

So asking, if there are options to modify the container further. The easiest way would be to provide a custom path for the mongodb.conf-file, which is pointing to the e.g. data-directory.

My draft-config is looking like the following:
```
systemLog:
  destination: file
  path: "/var/log/mongodb/mongodb.log"
  logAppend: true
storage:
  dbPath: "/var/lib/mongodb"
  journal:
    enabled: false
  syncPeriodSecs: 600
net:
  bindIp: 127.0.0.1
  port: 27117
setParameter:
  diagnosticDataCollectionEnabled: false
```
But currently, I'm not able to get this bound.
