### ISSUE TITLE
latest doesn't give me latest and use uid/gid is hard coded

### ISSUE THREAD

**Issue by gctwnl** [jacobalberty/unifi-docker#620]
### Operating system

Ubuntu 22.04.1 LTS

### UniFi Tag

latest

### Docker run

Standard docker compose currently latest, copied verbatim

### Bug description

I'm still getting the 7.2.95 running with the new compose file. Shouldn't I be getting 7.3?

I'm also seeing 
```
unificontroller_controller  | 2022/12/21 21:54:48 Chown 999:999 /unifi
unificontroller_controller  | [2022-12-21 21:54:48,721] <docker-entrypoint> Starting unifi controller service.

```
But my unifi user has UID 118 (GID 123)

This was my previous compose file:
```
networks:
  rna-docker-exposed:
    external: true # means it is a fixed docker network created with "docker network create rna-docker-exposed"
    name: rna-docker-exposed # docker create network rna-docker-exposed

version: "2.1"
services:
  unifi-controller:
    image: jacobalberty/unifi:latest
    container_name: unifi-controller
    environment:
      - TZ=Europe/Amsterdam
      - RUNAS_UID0=false
      # Sadly, we cannot run this as non-root as the container itself wants to do setuid to a non-root uid
      - UNIFI_UID=118
      - UNIFI_GID=123
      # This is for the import SSL script:
      - UNIFI_HOSTNAME=snape.rna.nl
    volumes:
      - /srv/docker/unificontroller/unifi:/unifi
      - /etc/letsencrypt/live/snape.rna.nl/fullchain.pem:/etc/letsencrypt/live/snape.rna.nl/fullchain.pem:ro
      - /etc/letsencrypt/live/snape.rna.nl/privkey.pem:/etc/letsencrypt/live/snape.rna.nl/privkey.pem:ro
    ports: # also need entrypoints in traefik
      - 1900:1900/udp   # optional? (required to make application discoverable on L2 net)
      - 3478:3478/udp   # traefik entrypoint: unifistun
      - 5514:5514/udp   # optional
      - 6789:6789       # optional
      - 8080:8080       # traefik entrypoint: unifidevice
      - 8443:8443       # traefik entrypoint: unifiwebadmin
#      - 8843:8843 #optional
#      - 8880:8880 #optional
      - 10001:10001/udp # traefik entrypoint: unifidiscovery
    restart: unless-stopped
    networks:
      - rna-docker-exposed
```

### Steps to reproduce

Have a 7.2.95 compose file setup. Replace the compose file with the current default latest. But I suspect I am making a mistake and this is not a bug.

### Relevant log output

```shell
root@snape:/srv/docker/unificontroller# docker compose logs
unificontroller_controller  | 2022/12/21 21:54:48 Chown 999:999 /unifi
unificontroller_controller  | [2022-12-21 21:54:48,721] <docker-entrypoint> Starting unifi controller service.
unificontroller_logs        | ==> /unifi/log/migration.log <==
unificontroller_logs        | 
unificontroller_logs        | ==> /unifi/log/server.log <==
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[U7EDU] new version (4.3.28.11361) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[USL16P] new version (6.3.13.14104) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[UCK] new version (1.1.19.f4a17b0) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[USL16PB] new version (6.3.13.14104) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[USL24PB] new version (6.3.13.14104) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[U6ENTIW] new version (6.2.49.14111) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[USL24B] new version (6.3.13.14104) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[USPRPSP] new version (6.3.13.14104) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[UBBXG] new version (1.0.10.284) is available
unificontroller_logs        | [2022-12-21T21:51:43,202] <autoupdate-check> INFO  productinfo - firmware[UP6] new version (2.2.3.519) is available
unificontroller_logs        | [2022-12-21T21:54:50,430] <launcher> INFO  tomcat - Adding basic REST API support during the startup
unificontroller_logs        | [2022-12-21T21:54:50,865] <launcher> INFO  system - Tomcat startup took 725ms
unificontroller_logs        | [2022-12-21T21:54:50,866] <launcher> INFO  db     - Version 7.2.95 has not changed, skipping migration
unificontroller_logs        | [2022-12-21T21:54:50,880] <launcher> INFO  tomcat - Adding basic REST API support during the startup
unificontroller_logs        | [2022-12-21T21:54:51,978] <launcher> INFO  db     - waiting for db connection...
unificontroller_logs        | [2022-12-21T21:54:52,479] <launcher> INFO  db     - Connecting to mongodb://mongo/unifi
unificontroller_logs        | [2022-12-21T21:54:52,645] <launcher> INFO  db     - setting mongodb features compatibility version to 3.6
unificontroller_logs        | [2022-12-21T21:54:52,749] <launcher> INFO  system - ======================================================================
unificontroller_logs        | [2022-12-21T21:54:52,750] <launcher> INFO  system - UniFi 7.2.95 (build atag_7.2.95_18699 - release/release) is started
unificontroller_logs        | [2022-12-21T21:54:52,750] <launcher> INFO  system - ======================================================================
unificontroller_logs        | [2022-12-21T21:54:52,750] <launcher> INFO  system - BASE dir:/usr/lib/unifi
unificontroller_logs        | [2022-12-21T21:54:52,782] <launcher> INFO  system - Current System IP: 172.24.0.3
unificontroller_logs        | [2022-12-21T21:54:52,782] <launcher> INFO  system - Hostname: bd495f128c5a
```
