### ISSUE TITLE
No APs showing up in Controller

### ISSUE THREAD

**Issue by Wairu** [jacobalberty/unifi-docker#650]
### Operating system

 DietPi v8.15.2

### UniFi Tag

7.3

### Docker run

docker-compose up -d

### Bug description

**Device**: `Ubiquiti U6-LITE UniFi 6 Lite Access Point`
**Problem**: Unable to be detected among UniFi devices

In my `docker-compose.yaml` file:
```
version: '3.7'
services:
  unifi:
    image: jacobalberty/unifi:7.3
    container_name: "unifi"
    restart: always
    volumes:
      - ./data:/unifi
    ports:
      - 3478:3478/udp
      - 6789:6789/tcp
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 8843:8843/tcp
      - 8880:8880/tcp
      - 1000:1000/udp
    environment:
      - TZ=Europe/Budapest
```

These are the configuration parameters I have set there as I was following [This tutorial](https://youtu.be/67URjZ3FP90?t=642) with a tiny modification on version number, and TZ difference.

### Steps to reproduce

`cd ~/Docker/unifi/`
`docker-compose up -d`

- Access the Controller hosted from my Raspberry Pi4 with its IP:8443
- Enter credentials
- On the left pane navigate to `UNIFI DEVICES`
- Only the UniFi Switch 24 is the one device that is visible, which has been adopted a year ago successfully.

I checked it on iPadOS's Unifi app, it only showed up visible only to be made "Independent Device"
