### ISSUE TITLE
 <device-state-check> WARN  monitor - Skipping check for <mac_address>, could not acquire lock

### ISSUE THREAD

**Issue by betterbeready** [jacobalberty/unifi-docker#674]
### Operating system

Docker version 24.0.4 on Debian 11

### UniFi Tag

unifi:v7.4

### Docker run

docker compose up -d

### Bug description

Since the latest updates, I'm facing this weird issue that's causing Mongodb to saturate the container's ram and oftern the controller's stops responding.

![image](https://github.com/jacobalberty/unifi-docker/assets/141132632/c10a3ab0-ced2-4af0-8e02-0458c03ee73a)

I've modified the original docker-compose.yml by adding a memory limit on mongo service (4096M) and set on controller's env LOROFDEVICES: 'true' (xmx on 6gb).

I think memory get saturated because of the error loop ongoing in logs.

Got something like 350 uaps, 100 sites and a lot of clients connected, it crashes even during nighttime with very low clients online.

I've already tried to modify _system.properties_ manually, in particular using these parameters:
_Nd=number of devices_

```
unifi.xms=[Nd8Mb]

unifi.xmx=[Nd16Mb]

unifi.xss = 1024

inform.num_thread=[2Nd]

inform.max_keep_alive_request=[Nd]

inform_stat.thread_queue_size=[Nd]

inform_stat.num_threads=[Nd/2]
```

_I never had this issue with previous version of the controller.(v6)_

### Steps to reproduce

It's just appear after few minutes the compose starts up.

### Relevant log output

```shell
unifi-logs-1        | [2023-08-01 11:56:10,868] <device-state-check> WARN  monitor - Skipping check for <mac_address>, could not acquire lock
unifi-logs-1        | com.ubnt.service.lock.String: Failed to acquire lock before timeout
unifi-logs-1        |   at com.ubnt.service.lock.new.Ô00000(Unknown Source)
unifi-logs-1        |   at com.ubnt.service.lock.ooOO.Ò00000(Unknown Source)
unifi-logs-1        |   at com.ubnt.service.lock.H.while(Unknown Source)
unifi-logs-1        |   at com.ubnt.service.lock.H.OO0000(Unknown Source)
unifi-logs-1        |   at com.ubnt.service.lock.H.õO0000(Unknown Source)
unifi-logs-1        |   at com.ubnt.service.devmgr.O0oO.Ø00000(Unknown Source)
unifi-logs-1        |   at com.ubnt.service.devmgr._A.oO0000(Unknown Source)
unifi-logs-1        |   at com.ubnt.service.devmgr._A.Ø00000(Unknown Source)
unifi-logs-1        |   at com.ubnt.ace.Object$_OOo.run(Unknown Source)
unifi-logs-1        |   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
unifi-logs-1        |   at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
unifi-logs-1        |   at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
unifi-logs-1        |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
unifi-logs-1        |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
unifi-logs-1        |   at java.base/java.lang.Thread.run(Thread.java:829)
```

Update:

I added some "tweaks" into JAVA_EXTRA_OPTS that seems to mitigate a bit this annoying issue:
extract from my edited docker-compose.yml:

[...]
```
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      LOTOFDEVICES: 'true'
      JVM_INIT_HEAP_SIZE: 6G
      JVM_MAX_HEAP_SIZE: 6G
      JVM_EXTRA_OPTS: "-XX:ParallelGCThreads=4 -Djava.awt.headless=true -Xss1280k -Dfile.encoding=UTF-8 -Dlog4j2.formatMsgNoLookups=true -XX:MaxMetaspaceSize=512M -XX:+UseG1GC -XX:+AggressiveOpts -XX:+UseStringDeduplication" 
```
[...]

This will not eradicate the errors instead consider as a softner.
