### ISSUE TITLE
system.properties changes do not stick

### ISSUE THREAD

**Issue by pho3nixf1re** [jacobalberty/unifi-docker#69]
### Host operating system

Debian GNU/Linux 8

### What tag are you using

Example: `latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```yml
unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:latest
    network_mode: host
    restart: always
    volumes:
      - ./data/unifi:/unifi
      - ./data/letsencrypt/certs/gateway.feliciterra.com:/unifi/cert
```

Note: A screenshot of your configuration page if using a gui is acceptable

### What do you expect to happen?

`system.properties` to keep the settings that I change.

### What actually happens?

`system.properties` is set back to default (everything commented) and my changes are removed.
