### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH with letsencrypt certificates

### ISSUE THREAD

**Issue by pho3nixf1re** [jacobalberty/unifi-docker#70]
### Host operating system

Debian GNU/Linux 8

### What tag are you using

latest

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

```yaml
version: '3'
services:
  letsencrypt:
    container_name: letsencrypt
    image: csmith/letsencrypt-lexicon:latest
    restart: always
    environment:
      PROVIDER: 'dnsimple'
      ACCEPT_CA_TERMS: 'true'
    env_file:
      - .env
    volumes:
      - ./data/letsencrypt:/letsencrypt
  unifi:
    container_name: unifi
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:latest
    network_mode: host
    restart: always
    volumes:
      - ./data/unifi:/unifi
      - ./data/letsencrypt/certs/gateway.feliciterra.com:/unifi/cert
```

### What do you expect to happen?

For the TLS certs to work when visiting with a browser.

### What actually happens?

I've tried a variety of things here but can't seem to get anything to work. The error displayed in chrome is `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` and in Firefox it's `SSL_ERROR_NO_CYPHER_OVERLAP`. If I remove my letsencrypt certificates everything works fine with the self-signed cert. It seems that the letsencrypt certs are broken when imported into unifi. These exact same certs I have mounted in other services and running just fine. I have rebuilt the container numerous times all with the same results.
