### ISSUE TITLE
Migrate from built-in MongoDB Server to own container

### ISSUE THREAD

**Issue by schleyk** [jacobalberty/unifi-docker#701]
Hi guys,

I have a Unifi Controller which is currently running as "All-in-One run as root Container".
What would be the easiest way to split the Unifi controller and MongoDB into individual containers?

Create a backup via Unifi Software and restore it on a newly created [docker-compose](https://github.com/jacobalberty/unifi-docker/blob/master/docker-compose.yml) stack?

Here is the current docker-compose file:
```
version: '3.5'

services:
    unifi:
      restart: always
      image: jacobalberty/unifi
      network_mode: "host"
      volumes:
          - "./unifi:/unifi"
```

Thanks for your ideas.
