### ISSUE TITLE
Docker compose and documentation update

### ISSUE THREAD

**Issue by itmp-git** [jacobalberty/unifi-docker#732]
Hi, a very small thing (I know everyone is busy) but if possible, can you please update the docker compose file (looks very old, 4y) and also the install documentation? It is not very clear for the current version since a lot of changes from 7 -> 8.

Even the text on main page reads: "The current "latest" version is Unifi Controller 7.5.176"
Thank you for all the great work on this project!

**Comment by Gamertech** [comment]
Nothing wrong with the docker-compose file. No point changing something just for the sake of refreshing the date on it.

It's fully compliant with the latest compose spec so really all that could be changed without breaking it is removing the first version line which has zero effect on anything as it's ignored nowadays anyway.

As for the version in the readme, whoops, looks like I missed that last PR.

**Comment by itmp-git** [comment]
Hi @Gamertech , sorry, maybe I am wrong, but on the main page documentation, in section "Running Unifi-in-Docker" there is the command below, and in the compose file it is different, starts multiple containers, etc.

No compose file for just the one container that wraps everything.
Using a Synology NAS we have the option to create a "project" and provide a file, than it creates everything automatically.

-------
Each time you want to start Unifi, use this command. Each of the options is described below.

docker run -d --init \
   --restart=unless-stopped \
   -p 8080:8080 -p 8443:8443 -p 3478:3478/udp \
   -e TZ='Africa/Johannesburg' \
   -v ~/unifi:/unifi \
   --user unifi \
   --name unifi \
   jacobalberty/unifi

**Comment by itmp-git** [comment]
Also there is mentioned:
"One-time setup: create the unifi directory on the Docker host. Within that directory, **create two sub-directories**: data and log."
 - but in the "_Running Unifi-in-Docker_" there is only /unifi

Thank you.

**Comment by Gamertech** [comment]
Ah, I see what you mean now. Fair enough. Will need to look into that.

**Comment by Fraddles** [comment]
WOW, I had no idea I had been using this container for that long...  Here is my simple compose file that worked perfectly until a couple of weeks ago when I migrated my controller to Unraid...  Is it even supposed to work without a Mongo container?
```
version: '3.9'

services:
  unifi:
    container_name: UniFi
    hostname: UniFi
    image: jacobalberty/unifi
    user: 1001:1001
    volumes:
      - ./data:/unifi
      - ./run:/var/run/unifi
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      dockermacvlan:
        ipv4_address: 192.168.0.###
    restart: always
    environment:
      - UNIFI_UID=1001
      - UNIFI_GID=1001

networks:
  dockermacvlan:
    external: true
```
https://github.com/Fraddles/Home-Automation/tree/main/UniFi%20Controller
