### ISSUE TITLE
Latest versions are not available in Docker Hub for arch. linux/arm/v7

### ISSUE THREAD

**Issue by bmonteiro** [jacobalberty/unifi-docker#734]
### Operating system

Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

### UniFi Tag

v8

### Docker run

docker run -d --init --restart=unless-stopped -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -v ~/unifi:/unifi --user unifi --name unifi jacobalberty/unifi:v8.x.x

### Bug description

Latest versions are not available in Docker Hub for arch. linux/arm/v7

Maybe related with MongoDB ? 

"I do not see much of a path forward for armhf due to the lack of mongodb support for 32 bit arm, but I will support it as long as feasibly possible, for now that date seems to be expiration of support for ubuntu 18.04."

**Comment by esand** [comment]
Unless you redacted the numbers in the tag, 8.x.x is not a valid tag. You need to specify 8.1.113, 8.1 or latest. You can confirm valid tags by checking on Docker Hub, then going to the Tags tab to confirm which tags are available for the image.

**Comment by tylerbergmann** [comment]
Just dropping in to say that I'm also having the same issue, nearly identical specs and details! 
Linux 6.1.21-v7+

**Comment by Sysadminfromhell** [comment]
You can See on dockerhub that thee latest an everythign after v7.4 is not build with armv7, I guess thats due to the fact that MongoDB dropped support ant after 7,4 (7.5 and up) mongodb needs to be version 3.6
The best way is to migrate to a supported platform like arm64 (Rasperry pi 4 in arm64 mode) or amd64.

**Comment by Sysadminfromhell** [comment]
If you want you can try to built the dockerimage yourself and see why it isn't prebuilt anymore.
use this command in the location where the dockerfile is located to get the build for your desired plattform:
`docker buildx build -f Dockerfile . --platform linux/arm/v7`

**Comment by sayotte** [comment]
Running this on a Raspberry Pi 4 with Docker Compose, I added `platform: linux/arm64` under the "controller" service in my `docker-compose.yaml` to force it to download the arm64 binary (which does work).

Full config as follows:
```yaml
version: '2.3'
services:
  controller:
    image: "jacobalberty/unifi:v7"
    platform: linux/arm64
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - unifi:/unifi
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery

volumes:
  unifi:

networks:
  unifi:
```
