### ISSUE TITLE
Enable AP log collection for this docker container

### ISSUE THREAD

**Issue by jakhei89** [jacobalberty/unifi-docker#757]
The docker image does not collect data from access points, the path` /logs/remote` is empty.
These logs are required when interacting with the UniFi support, after some troubleshooting we've figured out, that port 5514 (UDP) needs to be opened on the container. Once that's done, the logs are collected correctly.
See also required ports: https://help.ui.com/hc/en-us/articles/218506997-Required-Ports-Reference

TLDR: the fix is, to add port 5514/udp to docker-compose or the run command:

```
version: '2'
services:
 unifi-controller:
   container_name: unifi.controller
   image: jacobalberty/unifi:latest
   restart: always
   volumes:
     - './:/unifi'
   ports:
     - '3478:3478/udp'
     - '8889:8080/tcp'
     - '8444:8443/tcp'
     - '5514:5514/udp'
   environment:
     - TZ=Europe/Vienna
   labels:
     - 'unifi-controller'
```
