### ISSUE TITLE
How to run container behind proxy?

### ISSUE THREAD

**Issue by twistor** [jacobalberty/unifi-docker#78]
I have a server running various things and use nginx to proxy to services based on hostname. When I try to proxy requests to localhost 8443 the page loads, but I get a 403 when trying to login. Is this configuration supported?

Ideally, I could turn off tls and just proxy to 8080, since nginx handles certs, but anyway I can get it to work is fine.

### Host operating system
Ubuntu 17.10

### What tag are you using
stable

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
docker run --restart=always --init -p 6789:6789 -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='America/Los_Angeles' -v /path/unifi:/unifi --env RUNAS_UID0=false --name unifi -d jacobalberty/unifi:stable

**Comment by jacobalberty** [comment]
There's nothing about the image itself that would break using a reverse proxy, You've likely got some issue with your nginx configuration. I do see some people who had similar issues on the UniFi forums https://community.ubnt.com/t5/UniFi-Wireless/NGINX-Support/m-p/1547962/highlight/true#M157900 Theres a couple people who posted their working configuration, but I don't see a specific fix for the guy who originally requested.

**Comment by twistor** [comment]
Thanks for the assistance.

For those that find this later, this is required:
`proxy_set_header HOST $http_host;`

Not sure why I didn't think of it.

**Comment by mgscreativa** [comment]
Hi @twistor where do you exactly put that in the docker-compose.yml file? Would you be so kind to point me that out? This is my docker-compose.yml file. Thanks!

```
#docker-compose up -d
version: '2'
services:
    web:
        image: 'jacobalberty/unifi:latest'
        restart: always
        hostname: 'cam.mgscreativa.com.ar'
        container_name: unifi
        environment:
            - RUNAS_UID0=false
            - TZ='America/Buenos_Aires'
            - CERTNAME=unifi.mgscreativa.com.ar.crt
            - CERT_IS_CHAIN=true
        extra_hosts:
            - 'lucas.mgscreativa.com.ar:10.0.0.77'
        ports:
            - '2080:8080'
            - '2443:8443'
            - '2843:8843'
            - '2880:8880'
            - '2478:3478/udp'
            - '2789:6789'
            - '20001:10001/udp'
        volumes:
            - '/media/data/unifi/data:/unifi/data'
            - '/media/data/unifi/log:/unifi/log'
            - '/media/data/unifi/cert:/unifi/cert'
            - '/media/data/unifi/init.d:/unifi/init.d'
```
