### ISSUE TITLE
SMTP mail timeout error

### ISSUE THREAD

**Issue by ThomDietrich** [jacobalberty/unifi-docker#792]
### Operating system

Ubuntu 22.04.5 LTS

### UniFi Tag

v9.0.114

### Docker run

```yaml

  controller:
    # https://hub.docker.com/r/jacobalberty/unifi/tags
    #image: jacobalberty/unifi:latest
    image: jacobalberty/unifi:v9.0.114
    depends_on:
      - mongo
      - dnsrobocert
    init: true
    networks:
      - unifi7
    restart: always
    volumes:
      - dir:/unifi
      - data:/unifi/data
      - log:/unifi/log
      #- cert:/unifi/cert
      - ./letsencrypt:/unifi/cert
      - init:/unifi/init.d
      - run:/var/run/unifi
      # Mount local folder for backups and autobackups
      - ./backup:/unifi/data/backup
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
      TZ: "Europe/Berlin"
      UNIFI_HTTPS_PORT: 443
      # UNIFI_STDOUT: true
    ports:
      - "21.61.24.36:3478:3478/udp"    # STUN
      - "21.61.24.36:6789:6789/tcp"    # Speed test
      - "21.61.24.36:8080:8080/tcp"    # Device/ controller comm.
      - "21.61.24.36:8443:8443/tcp"    # Controller GUI/API as seen in a web browser
      - "21.61.24.36:8880:8880/tcp"    # HTTP portal redirection
      - "21.61.24.36:8843:8843/tcp"    # HTTPS portal redirection
      - "21.61.24.36:10001:10001/udp"  # AP discovery
      - "21.61.24.36:443:443/tcp"      # Controller GUI/API as seen in a web browser
```
### Bug description

Hey Jacob!
Apologies if this turns out to not be an issue with your image.

I have difficulties to set up smtp mail sending. In the UI I have set up "Custom Server" with various variations of smtp settings (starttls/ssl, ports, hosts, etc). The "send test mail" functions errors out with "Email failed to send" and this is seen in the log:

### Steps to reproduce

See above

### Relevant log output

```log
controller-1   | [2025-03-11 10:42:50,983] <webapi-2> WARN  event  - Failed to send email. Messaging exception
controller-1   | org.eclipse.angus.mail.util.MailConnectException: Couldn't connect to host, port: mail.xyz.de, 465; timeout 10000
controller-1   |        at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2243)
controller-1   |        at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:729)
controller-1   |        at jakarta.mail.Service.connect(Service.java:367)
controller-1   |        at jakarta.mail.Service.connect(Service.java:225)
controller-1   |        at jakarta.mail.Service.connect(Service.java:174)
controller-1   |        at com.ubnt.service.mail.E.sendMail(Unknown Source)
controller-1   |        at com.ubnt.service.mail.A.ø00000(Unknown Source)
controller-1   |        at com.ubnt.service.mail.A.Ô00000(Unknown Source)
controller-1   |        at com.ubnt.service.config.thisnew.forprivate(Unknown Source)
controller-1   |        at com.ubnt.ace.api.M.if(Unknown Source)
controller-1   |        at com.ubnt.ace.api.ApiServlet.service(Unknown Source)
controller-1   |        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
controller-1   |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
controller-1   |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
controller-1   |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
controller-1   |        at com.ubnt.service.trace.requestmetrics.new.doFilter(Unknown Source)
controller-1   |        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:362)
controller-1   |        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:278)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
controller-1   |        at com.ubnt.ace.view.AuthFilter.doFilter(Unknown Source)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
controller-1   |        at com.ubnt.ace.view.UbiosHttpsFilter.doFilter(Unknown Source)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
controller-1   |        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:331)
controller-1   |        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:158)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
controller-1   |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
controller-1   |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
controller-1   |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
controller-1   |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
controller-1   |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
controller-1   |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
controller-1   |        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:267)
controller-1   |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
controller-1   |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
controller-1   |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397)
controller-1   |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
controller-1   |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
controller-1   |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
controller-1   |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
controller-1   |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
controller-1   |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
controller-1   |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
controller-1   |        at java.base/java.lang.Thread.run(Thread.java:840)
controller-1   | Caused by: java.net.SocketTimeoutException: Connect timed out
controller-1   |        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
controller-1   |        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
controller-1   |        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
controller-1   |        at java.base/java.net.Socket.connect(Socket.java:633)
controller-1   |        at org.eclipse.angus.mail.util.SocketFetcher.createSocket(SocketFetcher.java:366)
controller-1   |        at org.eclipse.angus.mail.util.SocketFetcher.getSocket(SocketFetcher.java:243)
controller-1   |        at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2193)
controller-1   |        ... 52 common frames omitted
controller-1   | [2025-03-11 10:42:50,984] <webapi-2> WARN  event  - fail to send email: api.err.SmtpSendFailed
```
